name: argos
version: 0.1.0.0
github: "githubuser/argos"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
    - README.md
    - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/argos#readme>

dependencies:
    - base >= 4.7 && < 5
    - containers <= 0.6.4.1
    - hspec
    - optparse-applicative <= 0.16.1.0
    - parsec <= 3.1.14.0
    - transformers <= 0.5.6.2

library:
    source-dirs: src

executables:
    argos-exe:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - argos

tests:
    argos-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - argos
