name: argos
version: 2.0.0
github: "aleperaltabazas/argos"
license: BSD3
author: "Alejandro Peralta Bazas"
maintainer: "aleperaltabazas@gmail.com"
copyright: "2021 Alejandro Peralta Bazas"

extra-source-files:
    - README.md
    - ChangeLog.md

synopsis: Bash autocompletion script generation from a tree-like structure
category: CLI, Options, Parsing

description: Please see the README on GitHub at <https://github.com/aleperaltabazas/argos#readme>

dependencies:
    - base >= 4.7 && < 5
    - containers <= 0.6.4.1
    - directory <= 1.3.6.0
    - hspec
    - optparse-applicative <= 0.16.1.0
    - parsec <= 3.1.14.0
    - regex-base <= 0.94.0.0
    - regex-posix <= 0.96.0.0
    - string-interpolate <= 0.2.1.0
    - transformers <= 0.5.6.2

library:
    source-dirs: src

executables:
    argos-exe:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - argos

tests:
    argos-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - argos
